# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
    # ./mnt-filesystems/qnap-ssh.nix
    #./mnt-filesystems/temu-stick.nix
    ./mnt-filesystems/optus-usb.nix
    ./mnt-filesystems/qnap-server.nix
    ./mnt-filesystems/qnap_nfs_public.nix
    ./mnt-filesystems/secrets.nix
  ];

  boot = {
    initrd = {
      systemd.enable = true;
      # generator = "dracut"; # 🔥 this activates dracut
      availableKernelModules = [
        "ahci"
        "nvme"
        "sd_mod"
        "uas"
        "usbhid"
        "xhci_pci"

      ];

      kernelModules = [

      ];

      systemd.extraConfig = ''
        DefaultTimeoutStopSec=1s
      '';
    };
    kernelParams = [
      #"mem_sleep_default=s2idle"
      #"nvme_core.default_ps_max_latency_us=0"
      # "pcie_aspm=off"
      # "scsi_mod.use_blk_mq=Y"
    ];

    supportedFilesystems = [
      "cifs"
      "nfs"

    ];
    kernelModules = [
      "kvm-intel"

    ];
    extraModulePackages = [

    ];
    kernel.sysctl = {
      "net.core.default_qdisc" = "fq_codel";
      "net.core.rmem_max" = 16777216;
      "net.core.wmem_max" = 16777216;
      "net.ipv4.ip_forward" = 1;
      "net.ipv4.tcp_congestion_control" = "bbr";
      "net.ipv4.tcp_ecn" = 0;
      "net.ipv4.tcp_mtu_probing" = 0;
      "net.ipv4.tcp_rmem" = "4096 87380 16777216";
      "net.ipv4.tcp_wmem" = "4096 65536 16777216";
    };
  };

  # ----------------------------------------------- #
  # NixOS Partitions
  # ----------------------------------------------- #

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/b3415f7d-f699-42ab-8dd1-13680aa71128";
    fsType = "ext4";
    options = [
      "defaults"
      "noatime"

    ];
  };
  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/36CB-3BA0";
    fsType = "vfat";
    options = [
      "dmask=0077"
      "fmask=0077"

    ];
  };

  swapDevices = [ ];

  networking.useDHCP = lib.mkDefault true;
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";

  powerManagement.cpuFreqGovernor = lib.mkDefault "performance";
  hardware = {
    cpu.intel.updateMicrocode =
      lib.mkDefault config.hardware.enableRedistributableFirmware;
    bluetooth.enable = true;
    bluetooth.powerOnBoot = true;
    enableRedistributableFirmware = true;
    # keyboard.qmk.enable = true;
  };
  # local.hardware-clock.enable = false;
}
